from lib.Exceptions.GeneralExceptions import GeneralExceptions


class ValidationException(GeneralExceptions):
    pass
